<?php
	session_start();

	$searchQuery = $_GET['query'];
		 
	require_once('tcpdf/tcpdf.php');
			
	$pdf = 
		new TCPDF(
			$orientation =	'L', 
			$unit = 		'mm', 
			$format = 		'folio', 
			$unicode =		'true', 
			$encoding =		'UTF-8', 
			$diskcache =	false, 
			$pdfa =			false
		);
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
	$pdf->SetCreator(PDF_CREATOR);
	$pdf->SetAuthor('MedTrack Team');
	$pdf->SetTitle('Inventory Report');
	$pdf->SetSubject('Inventory Report');	
	$pdf->SetFont('Helvetica', '', 10);
	
	$pdf->SetPrintHeader(false);
	$pdf->SetPrintFooter(false);
	
	$pdf->SetMargins(8, 8, 8, 8);
	
	$pdf->AddPage();
			
	$html = '
		<html>
			<head>
				<style>
					td{ text-align: center; }
				</style>
			</head>	
			<body>
				<h1>Eligible Products</h1>';
						
				date_default_timezone_set("Asia/Manila");
										
	$html .= 
				'<h4>Date Generated: ' . date("m/d/Y") . ' ' . date("h:i a") . '</h4>
				<h4>Generated by: ' . $_SESSION['fullname'] . '</h4>
				<div style="margin-bottom:20px"></div>
					
				<table border="1" cellpadding="8">
					<tr>
						<td><b>No.</b></td>
						<td><b>Item Code</b></td>
						<td><b>Generic Name</b></td>
						<td><b>Brand Name</b></td>
						<td><b>Dosage</b></td>
						<td><b>Type</b></td>
						<td><b>Classification</b></td>
					</tr>';
							
	include_once('./_connect.php');	
						
	$sql = 
		"SELECT * 
		FROM producttable, dynamicproducttable, vendorordertable
		WHERE producttable.productId = dynamicproducttable.productId 
		AND producttable.productId = vendorordertable.productId
		AND dynamicproducttable.sellingPrice <> 0
		AND vendorordertable.pricePerUnit <> 0
		ORDER BY producttable.productId";
	$result = mysqli_query($connect, $sql);
					
	$withElements = false;
	$queryCount = 0;
	while($row = mysqli_fetch_array($result)) {
		$withElements = true;
		$queryCount++;
		
	$html .='
					<tr nobr="true"> 
						<td>' . $queryCount . '</td>
						<td>' . $row['productId'] . '</td>
						<td>' . $row['genericName'] . '</td>
						<td>' . $row['brandName'] . '</td>
						<td>' . $row['dosage'] . '</td>
						<td>' . $row['type'] . '</td>
						<td>' . $row['classification'] . '</td>
					</tr>' ;
	}
	
	$html .='
				</table>
			</body>
		<html>';
			
	
	ob_clean(); 		
	
	$pdf->writeHTML(
		$html,
		$ln = true,
		$fill = false,
		$reseth = false,
		$cell = false,
		$align = '' );
	$pdf->lastPage();
	
	ob_end_clean();
	
	$pdf->Output('Inventory Report.pdf','I');