<?php
	session_start();

	$searchQuery = $_GET['query'];
		 
	require_once('tcpdf/tcpdf.php');
			
	$pdf = 
		new TCPDF(
			$orientation =	'L', 
			$unit = 		'mm', 
			$format = 		'folio', 
			$unicode =		'true', 
			$encoding =		'UTF-8', 
			$diskcache =	false, 
			$pdfa =			false
		);
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
	$pdf->SetCreator(PDF_CREATOR);
	$pdf->SetAuthor('MedTrack Team');
	$pdf->SetTitle('Delivery Report');
	$pdf->SetSubject('Delivery Report');	
	$pdf->SetFont('Helvetica', '', 10);
	
	$pdf->SetPrintHeader(false);
	$pdf->SetPrintFooter(false);
	
	$pdf->SetMargins(8, 8, 8, 8);
	
	$pdf->AddPage();
			
	$deliveryReportDay = substr($searchQuery,3,2);
	$deliveryReportMonth = substr($searchQuery,0,2);
	$deliveryReportYear = substr($searchQuery,6,4);
	
	$deliveryDate = '';
	switch ($deliveryReportMonth){
		case '01': $deliveryDate  .= "January"; break;
		case '02': $deliveryDate  .= "February"; break;
		case '03': $deliveryDate  .= "March"; break;
		case '04': $deliveryDate  .= "April"; break;
		case '05': $deliveryDate  .= "May"; break;
		case '06': $deliveryDate  .= "June"; break;
		case '07': $deliveryDate  .= "July"; break;
		case '08': $deliveryDate  .= "August"; break;
		case '09': $deliveryDate  .= "September"; break;
		case '10': $deliveryDate  .= "October"; break;
		case '11': $deliveryDate  .= "November"; break;
		case '12': $deliveryDate  .= "December"; break;
	}
	
	$deliveryDate .= " " . $deliveryReportDay . ", " . $deliveryReportYear;
			
	$html = '
		<html>
			<head>
				<style>
					td{ text-align: center; }
				</style>
			</head>	
			<body>
				<h1>Delivery Report</h1>
				<h4>Delivery Report for ' . $deliveryDate . '</h4>
				<div style="margin-bottom:20px"></div>';
						
				date_default_timezone_set("Asia/Manila");
										
	$html .= 
				'<h4>Date Generated: ' . date("m/d/Y") . ' ' . date("h:i a") . '</h4>
				<h4>Generated by: ' . $_SESSION['fullname'] . '</h4>
				<div style="margin-bottom:20px"></div>
					
				<table border="1" cellpadding="8">
					<tr>
						<td><b>Item Code</b></td>
						<td><b>Generic Name</b></td>
						<td><b>Brand Name</b></td>
						<td><b>Dosage</b></td>
						<td><b>Type</b></td>
						<td><b>Quantity</b></td>
						<td><b>Lot/Batch Number</b></td>
						<td><b>Expiration Date</b></td>
						<td><b>Received By</b></td>
						<td><b>Time Received</b></td>
					</tr>' ;
							
	include_once('./_connect.php');	
						
	if(strlen($searchQuery) == 10){
		$sql = 
			"SELECT * 
			FROM deliveriestable, producttable
			WHERE deliveriestable.productId = producttable.productId
			AND LEFT(deliveriestable.dateReceived,2) = '" . substr($searchQuery, 0, 2) . "' 
			AND MID(deliveriestable.dateReceived,4,2) = '" . substr($searchQuery, 3, 2) . "' 
			AND MID(deliveriestable.dateReceived,7,4) = '" . substr($searchQuery, 6, 4) . "';";
	} else if(strlen($searchQuery) == 7){
		$sql = 
			"SELECT * 
			FROM deliveriestable, producttable
			WHERE deliveriestable.productId = producttable.productId
			AND LEFT(deliveriestable.dateReceived,2) = '" . substr($searchQuery, 0, 2) . "' 
			AND MID(deliveriestable.dateReceived,7,4) = '" . substr($searchQuery, 3, 4) . "';";
	} else if(strlen($searchQuery) == 4){
		$sql = 
			"SELECT * 
			FROM deliveriestable, producttable
			WHERE deliveriestable.productId = producttable.productId
			AND MID(deliveriestable.dateReceived,7,4) = '" . substr($searchQuery, 0, 4) . "';";
	}				
	$result = mysqli_query($connect, $sql);
					
	$withElements = false;
	while($row = mysqli_fetch_array($result)) {
		$withElements = true;
							
	$html .='
					<tr nobr="true"> 
						<td>' . $row['productId'] . '</td>
						<td>' . $row['genericName'] . '</td>
						<td>' . $row['brandName'] . '</td>
						<td>' . $row['dosage'] . '</td>
						<td>' . $row['type'] . '</td>
						<td>' . $row['rdTotalUnits'] . '</td>
						<td>' . $row['lotNumber'] . '</td>
						<td>' . $row['expiryMonth'] . '-' . $row['expiryYear'] . '</td>
						<td>' . $row['receivedBy'] . '</td>
						<td>' . substr($row['timeReceived'],0,8) . " " . substr($row['timeReceived'],15,2) . '</td>
					</tr>' ;
	}
	
	if(!$withElements){
		$html .='
					<tr nobr="true"> 
						<td colspan="10">There are no entries for ' . $searchQuery . '</td>
					</tr>' ;
	}
	
	$html .='
				</table>
			</body>
		<html>';
			
	
	ob_clean(); 		
	
	$pdf->writeHTML(
		$html,
		$ln = true,
		$fill = false,
		$reseth = false,
		$cell = false,
		$align = '' );
	$pdf->lastPage();
	
	ob_end_clean();
	
	$pdf->Output('Delivery Report.pdf','I');