<?php
	session_start();
		 
	require_once('tcpdf/tcpdf.php');
			
	$pdf = 
		new TCPDF(
			$orientation =	'L', 
			$unit = 		'mm', 
			$format = 		'folio', 
			$unicode =		'true', 
			$encoding =		'UTF-8', 
			$diskcache =	false, 
			$pdfa =			false
		);
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
	$pdf->SetCreator(PDF_CREATOR);
	$pdf->SetAuthor('MedTrack Team');
	$pdf->SetTitle('Inventory Report');
	$pdf->SetSubject('Inventory Report');	
	$pdf->SetFont('Helvetica', '', 10);
	
	$pdf->SetPrintHeader(false);
	$pdf->SetPrintFooter(false);
	
	$pdf->SetMargins(8, 8, 8, 8);
	
	$pdf->AddPage();
			
	$html = '
		<html>
			<head>
				<style>
					table{
						text-align: center;
						display: table;
					}
				</style>
			</head>
			<body>
				<h1>Materials Creation Form</h1>';

	date_default_timezone_set("Asia/Manila");
	
	$html .= 
				'<h4>Date Generated: ' . date("m/d/Y") . ' ' . date("h:i a") . '</h4>
				<h4>Generated by: ' . $_SESSION['fullname'] . '</h4>
				<div style="margin-bottom:20px"></div>
								
				<table border="1" cellpadding="3">
					<tr>
						<td><b>Date Ordered</b></td>
						<td><b>Ordered By</b></td>
						<td><b>Item Code</b></td>
						<td><b>Generic name</b></td>
						<td><b>Brand name</b></td>
						<td><b>Unit Of Measure</b></td>
						<td><b>Vendor</b></td>
						<td><b>Bulk Unit Of Measure</b></td>
						<td><b>Number of Bulk Unit Ordered</b></td>
						<td><b>Reorder Level</b></td>
					</tr>' ;
						
		include_once('./_connect.php');
			
		$sql = 
			"SELECT * 
			FROM reordertable, producttable, vendorinfotable, dynamicproducttable
			WHERE reordertable.productId = producttable.productId 
			AND reordertable.productId = dynamicproducttable.productId
			AND reordertable.vendorId = vendorinfotable.vendorId
			AND reordertable.dateOrdered <> '00-00-0000'";
		$result = mysqli_query($connect, $sql);
					
		$withElements = false;
		while($row = mysqli_fetch_array($result)) {
			$withElements = true;
			
			$numberOfBulk = 0;
				if($row['rdNumOfBigBox'] == '-1'){
					$numberOfBulk = $row['roNumOfSmallBox'];
					$bulkUnit = 'Small Box';
				} else{
					$numberOfBulk = $row['roNumOfBigBox'];
					$bulkUnit = 'Big Box';
				}
							
	$html .='
					<tr nobr="true"> 
						<td>' . $row['dateOrdered'] . '<br>' . substr($row['timeOrdered'],0,8) . " " . substr($row['timeOrdered'],15,2) . '</td>
						<td>' . $row['requestedBy'] . '</td>
						<td>' . $row['productId'] . '</td>
						<td>' . $row['genericName'] . '</td>
						<td>' . $row['brandName'] . '</td>
						<td>' . $row['dosage'] . ", " . $row['type'] . '</td>
						<td>' . $row['vendorName'] . '</td>
						<td>' . $bulkUnit . '</td>
						<td>' . $numberOfBulk . '</td>
						<td>' . $row['reorderLevel'] . '</td>
						
					</tr>' ;
		}
		if(!$withElements){
			$html .='
						<tr nobr="true"> 
							<td colspan="10">There are no ordered products</td>
						</tr>' ;
		}
		
	$html .='
				</table>
			</body>
		<html>';
			
	
	ob_clean(); 		
	
	$pdf->writeHTML(
		$html,
		$ln = true,
		$fill = false,
		$reseth = false,
		$cell = false,
		$align = '' );
	$pdf->lastPage();
	
	ob_end_clean();
	
	$pdf->Output('Materials Creation Report Report.pdf','I');